=== JFMAREN/ordinario-ftw/ciudades.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="lista_ciudades">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ciudad" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:string"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="tipo" type="xs:string"/>
              <xs:element name="region" type="xs:string"/>
              <xs:element name="imagen" type="xs:string"/>
              <xs:element name="descripcion" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JFMAREN/ordinario-ftw/ciudades.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_ciudades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ciudades.xsd">
    <ciudad>
        <id>c1</id>
        <nombre>Gran Trad</nombre>
        <tipo>Capital</tipo>
        <region>Región Central</region>
        <imagen>grand_trad.png</imagen>
        <descripcion>La majestuosa capital del Reino de Euchronia. Una imponente metrópolis fortificada donde se concentran los poderes políticos y religiosos, y donde inicia la carrera por el trono tras el funeral del rey.</descripcion>
    </ciudad>
    <ciudad>
        <id>c2</id>
        <nombre>Martira</nombre>
        <tipo>Provincia</tipo>
        <region>Región de los Lagos</region>
        <imagen>martira.png</imagen>
        <descripcion>Conocida como la antigua ciudad fortificada del viejo orden. Es una urbe semiárida famosa por sus tabernas y por albergar una densa población de diversas tribus bajo un ambiente tenso de desconfianza.</descripcion>
    </ciudad>
    <ciudad>
        <id>c3</id>
        <nombre>Puerto Brilehaven</nombre>
        <tipo>Portuaria</tipo>
        <region>Costa Oceánica</region>
        <imagen>brilehaven.png</imagen>
        <descripcion>La vibrante y caótica capital marítima del reino. Dividida drásticamente por canales de agua y estatus sociales, este puerto comercial es el punto estratégico de reunión para los aspirantes al trono.</descripcion>
    </ciudad>
    <ciudad>
        <id>c4</id>
        <nombre>Isla Virga</nombre>
        <tipo>Sagrada</tipo>
        <region>Mar de Estrellas</region>
        <imagen>isla_virga.png</imagen>
        <descripcion>Una recóndita y misteriosa isla tropical habitada por la tribu Mustari. Considerada tierra sagrada, es inmune a la influencia directa de la Iglesia y resguarda secretos antiguos sobre la magia del reino.</descripcion>
    </ciudad>
    <ciudad>
        <id>c5</id>
        <nombre>Altabury</nombre>
        <tipo>Provincia</tipo>
        <region>Tierras Gélidas</region>
        <imagen>altabury.png</imagen>
        <descripcion>Una hermosa pero implacable ciudad construida sobre las laderas de montañas nevadas perpetuas. Es un centro minero e industrial clave, famoso por sus talleres de forja y su clima gélido extremo.</descripcion>
    </ciudad>
</lista_ciudades>
